### ISSUE TITLE
How to run mulitple training processes

### ISSUE THREAD

**Issue by RubickH** [JDAI-CV/image-captioning#14]
Hi, I am very interested in your codes.
I successfully run the codes on four GPUs as the given example suggests.
However, when I want to run two training processes (each process takes two GPUs), I got errors in distributed parallel training.
 ```
File "main.py", line 354, in <module>
    trainer = Trainer(args)
  File "main.py", line 48, in __init__
    self.setup_network()
  File "main.py", line 98, in setup_network
    find_unused_parameters=True
  File "/home/huangyq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/home/huangyq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /tmp/pip-req-build-ocx5vxk7/torch/lib/c10d/../c10d/NCCLUtils.hpp:48, invalid argument
```
and
```
Traceback (most recent call last):
  File "main.py", line 352, in <module>
    trainer = Trainer(args)
  File "main.py", line 40, in __init__
    backend="nccl", init_method="env://"
  File "/home/huangyq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 400, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/huangyq/anaconda3/envs/py36/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
```

I wonder how I can solve these problems.
Thanks!
Looking forward to your reply ^_^

**Comment by YehLi** [comment]
master_port should be set to different numbers. Please try the following scripts:
    CUDA_VISIBLE_DEVICES=3,2 python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=12346 main.py --folder ./experiments/xlan
    CUDA_VISIBLE_DEVICES=1,0 python3 -m torch.distributed.launch --nproc_per_node=2 --master_port=12347 main.py --folder ./experiments/xlan

**Comment by RubickH** [comment]
Thanks!
